# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: TestTccDeployment

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: WindowsMachineFileCopy@2
  inputs:
    SourcePath: 'C:\Users\289391\Desktop\testtext.txt'
    MachineNames: |
      10.176.204.4, 
      10.176.204.6
    AdminUserName: 'QA\289391'
    AdminPassword: 'GvM^^Y7rYd^q&8'
    TargetPath: 'C:\Users\289391\testfolder'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
