# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: TestTccDeployment

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 10.176.204.4 
    sourceFolder: # string. Source folder. 
    contents: '**' # string. Required. Contents. Default: **.
    #targetFolder: # string. Target folder.

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
